services:
  - type: web
    name: sr-earning-hub
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        value: "8042982338"
      - key: ADMIN_KEY
        sync: false
      - key: DB_PATH
        value: "earning_hub.db"
